### ISSUE TITLE
Rails 7.1 return Enumerator instead of csv contents with config.streaming enabled

### ISSUE THREAD

**Issue by taketo1113** [aki77/csb#17]
When using Rails 7.1 and enabled csb config.streaming, it returns the wrong content which rendered only the Enumerator string (Enumerator#to_s) in a csv file.

It seems that the cause is the issue of Rails which doesn't render Enumerator in view correctly in Rails 7.1.
https://github.com/rails/rails/issues/50930

- rails = 7.1.x / streaming = true : fails
- rails = 7.1.x / streaming = false : works
- rails <=7.0.x: works

### Expected behavior
It return correct csv file.

### Actual behavior
It return csv file which content is `#<Enumerator:0xXXXXXX>`.
```
#<Enumerator:0x000000012cd3fd38>
```

### System configuration
- csb: 0.7.0
- rails 7.1.3.2
- ruby: 3.3.0

**Comment by taketo1113** [comment]
> It seems that the cause is the issue of Rails which doesn't render Enumerator in view correctly in Rails 7.1.
> [rails/rails#50930](https://github.com/rails/rails/issues/50930)

It seems that the Issue will fix next release (rails 7.1.4?)
https://github.com/rails/rails/commit/d8b2e584416db00d5bed349febc7783c477076d9
https://github.com/rails/rails/pull/51023

**Comment by aki77** [comment]
Thank you for the information. 
It has been fixed in v0.9.0.
